# Nixpacks configuration for Orderbook
# https://nixpacks.com/docs/configuration/file

[phases.setup]
nixPkgs = ["python312"]

[phases.install]
cmds = [
  "cd .. && pip install -r requirements.txt"
]

[start]
cmd = "cd .. && uvicorn orderbook.main:app --host 0.0.0.0 --port $PORT"
